# Numpy

NumPy is a Python package. It stands for 'Numerical Python'. It is a library consisting of multidimensional array objects and a collection of routines for processing of array.

In [1]:
#calling the Libraries
import numpy as np

# Ndarray
N-dimensional array type called ndarray.

syntax:
=====
np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

1. object  --->Any object exposing the array interface method returns an array, or any (nested) sequence.

2. dtype   --->Desired data type of array, optional

3. copy    --->Optional. By default (true), the object is copied

4. order   --->C (row major) or F (column major) or A (any) (default)

5. subok   --->By default, returned array forced to be a base class array. If true, sub-classes passed through

6. ndmin   --->Specifies minimum dimensions of resultant array

In [4]:
#ndarray in 1D
a = np.array([1,2,3]) 
a

array([1, 2, 3])

In [6]:
# more than one dimensions 
d = np.array([[1, 2], [3, 4]]) 
d

array([[1, 2],
       [3, 4]])

In [7]:
#ndarray using ndmin
a = np.array([1, 2, 3,4,5], ndmin = 2) 
a

array([[1, 2, 3, 4, 5]])

In [9]:
#ndarray using dtype parameter 
a = np.array([1, 2, 3], dtype = complex) 
a

array([1.+0.j, 2.+0.j, 3.+0.j])

# Data Types

1	bool_  --->Boolean (True or False) stored as a byte

2	int_--->Default integer type (same as C long; normally either int64 or int32)

3	intc--->Identical to C int (normally int32 or int64)

4	intp--->Integer used for indexing (same as C ssize_t; normally either int32 or int64)

5	int8--->Byte (-128 to 127)

6	int16--->Integer (-32768 to 32767)

7	int32--->Integer (-2147483648 to 2147483647)

8	int64--->Integer (-9223372036854775808 to 9223372036854775807)

9	uint8--->Unsigned integer (0 to 255)

10	uint16--->Unsigned integer (0 to 65535)

11	uint32--->Unsigned integer (0 to 4294967295)

12	uint64--->Unsigned integer (0 to 18446744073709551615)

13	float_--->Shorthand for float64

14	float16--->Half precision float: sign bit, 5 bits exponent, 10 bits mantissa

15	float32--->Single precision float: sign bit, 8 bits exponent, 23 bits mantissa

16	float64--->Double precision float: sign bit, 11 bits exponent, 52 bits mantissa

17	complex_--->Shorthand for complex128

18	complex64--->Complex number, represented by two 32-bit floats (real and imaginary components)

19	complex128--->Complex number, represented by two 64-bit floats (real and imaginary components)

Syntax:
=======
numpy.dtype(object, align, copy)

In [12]:
#For Example
a='a'
np.dtype(a) 

dtype('S')

Each built-in data type has a character code that uniquely identifies it.

'b' − boolean

'i' − (signed) integer

'u' − unsigned integer

'f' − floating-point

'c' − complex-floating point

'm' − timedelta

'M' − datetime

'O' − (Python) objects

'S', 'a' − (byte-)string

'U' − Unicode

'V' − raw data (void)

# Array Attributes

# ndarray.shape
This array attribute returns a tuple consisting of array dimensions. It can also be used to resize the array.

In [20]:
#Shape of the Array
a = np.array([[1,2,3],[4,5,6]]) 
a.shape

(2, 3)

In [22]:
#Resize the Shape of Array
a.shape = (3,2)
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
#Reshape of Array --> Resize and Reshape below are same o/p only
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

# ndarray.ndim
This array attribute returns the number of array dimensions.

In [28]:
#ndim will Dimensions of the Array
a = np.arange(24)
np.ndim(a)

1

In [29]:
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [26]:
b=a.reshape(2,3,4)
np.ndim(b)

3

In [27]:
b

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

# numpy.itemsize
This array attribute returns the length of each element of array in bytes.

In [31]:
x = np.array([1,2,3,4,5], dtype = np.int8) 
x.itemsize

1

# numpy.flags
The ndarray object has the following attributes. Its current values are returned by this function.

1	C_CONTIGUOUS (C)
The data is in a single, C-style contiguous segment

2	F_CONTIGUOUS (F)
The data is in a single, Fortran-style contiguous segment

3	OWNDATA (O)
The array owns the memory it uses or borrows it from another object

4	WRITEABLE (W)
The data area can be written to. Setting this to False locks the data, making it read-only

5	ALIGNED (A)
The data and all elements are aligned appropriately for the hardware

6	UPDATEIFCOPY (U)
This array is a copy of some other array. When this array is deallocated, the base array will be updated with the contents of this array



In [33]:
x = np.array([1,2,3,4,5]) 
x.flags

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False

# numpy.empty
It creates an uninitialized array of specified shape and dtype. It uses the following constructor −

syntax
======
numpy.empty(shape, dtype = float, order = 'C')

1. Shape--->Shape of an empty array in int or tuple of int

2. Dtype--->Desired output data type. Optional

3. Order--->'C' for C-style row-major array, 'F' for FORTRAN style column-major array

In [34]:
x = np.empty([3,2], dtype = int) 
x

array([[1, 2],
       [3, 4],
       [5, 6]])

# numpy.zeros
Returns a new array of specified size, filled with zeros.

syntax
======
numpy.zeros(shape, dtype = float, order = 'C')

In [35]:
x = np.zeros(5)
x

array([0., 0., 0., 0., 0.])

In [37]:
#Using dtype
x = np.zeros((5,), dtype = np.int) 
x

array([0, 0, 0, 0, 0])

In [41]:
x = np.zeros([2,2])
x

array([[0., 0.],
       [0., 0.]])

# numpy.ones
Returns a new array of specified size and type, filled with ones.

Syntax:
====
numpy.ones(shape, dtype = None, order = 'C')

In [42]:
x = np.ones(5) 
x

array([1., 1., 1., 1., 1.])

In [43]:
x = np.ones([2,2])
x

array([[1., 1.],
       [1., 1.]])

In [45]:
#Using dtype
x = np.ones((5,), dtype = np.int) 
x

array([1, 1, 1, 1, 1])

# Array From Existing Data

# numpy.asarray
This function is similar to numpy.array except for the fact that it has fewer parameters. This routine is useful for converting Python sequence into ndarray.

syntax:
======
numpy.asarray(a, dtype = None, order = None)

1. a ---->Input data in any form such as list, list of tuples, tuples, tuple of tuples or tuple of lists

2. dtype ---->By default, the data type of input data is applied to the resultant ndarray

3. order ---->C (row major) or F (column major). C is default

In [46]:
x = [1,2,3] 
np.asarray(x)

array([1, 2, 3])

# Numerical Ranges

# numpy.arange
This function returns an ndarray object containing evenly spaced values within a given range. The format of the function is as follows −

Syntax:
======
np.arange([start,] stop[, step,], dtype=None)

1. start : number, optional ---->Start of interval.  The interval includes this value.  The defaultstart value is 0.

2. stop : number ---->End of interval.  The interval does not include this value, except
    in some cases where `step` is not an integer and floating point
    round-off affects the length of `out`.
    
3. step : number, optional ---->Spacing between values. For any output `out`, this is the distance
    between two adjacent values, ``out[i+1] - out[i]``. The default
    step size is 1.  If `step` is specified as a position argument,
    `start` must also be given.
    
4. dtype : dtype ---->    The type of the output array.  If `dtype` is not given, infer the data
    type from the other input arguments.



In [47]:
#Arange
np.arange(5)

array([0, 1, 2, 3, 4])

In [48]:
# start and stop parameters with stepsize
x = np.arange(10,20,2) 
x

array([10, 12, 14, 16, 18])

# numpy.linspace
This function is similar to arange() function. In this function, instead of step size, the number of evenly spaced values between the interval is specified. The usage of this function is as follows −

Syntax:
======
np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)

1. start : scalar ---->
    The starting value of the sequence.
    
2. stop : scalar ---->
    The end value of the sequence, unless `endpoint` is set to False.
    In that case, the sequence consists of all but the last of ``num + 1``
    evenly spaced samples, so that `stop` is excluded.  Note that the step
    size changes when `endpoint` is False.

3. num : int, optional --->
    Number of samples to generate. Default is 50. Must be non-negative.
    
4. endpoint : bool, optional --->
   If True, `stop` is the last sample. Otherwise, it is not included.
    Default is True.
    
5. retstep : bool, optional --->
    If True, return (`samples`, `step`), where `step` is the spacing
    between samples.

In [50]:
x = np.linspace(10,20,5) 
x

array([10. , 12.5, 15. , 17.5, 20. ])

In [52]:
#Using Endpoint
x = np.linspace(10,20, 5, endpoint = False) 
x

array([10., 12., 14., 16., 18.])

In [53]:
#Using retstep
x = np.linspace(1,2,5, retstep = True) 
x

(array([1.  , 1.25, 1.5 , 1.75, 2.  ]), 0.25)

# numpy.logspace
This function returns an ndarray object that contains the numbers that are evenly spaced on a log scale. Start and stop endpoints of the scale are indices of the base, usually 10.

Syntax:
=======
np.logspace(start, stop, num=50, endpoint=True, base=10.0, dtype=None)

In [56]:
a = np.logspace(1.0, 2.0, 10) 
a

array([ 10.        ,  12.91549665,  16.68100537,  21.5443469 ,
        27.82559402,  35.93813664,  46.41588834,  59.94842503,
        77.42636827, 100.        ])

In [59]:
a = np.logspace(1,2,num = 10, base = 2) 
a

array([2.        , 2.16011948, 2.33305808, 2.5198421 , 2.72158   ,
       2.93946898, 3.1748021 , 3.42897593, 3.70349885, 4.        ])

# Indexing & Slicing

In [61]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
#slicing the single value
a[2]

2

In [68]:
# slice items between indexes with stepsize of index
a[2:10:2]

array([2, 4, 6, 8])

In [69]:
# slice items starting from index 
a[2:]

array([2, 3, 4, 5, 6, 7, 8, 9])

In [70]:
# slice items between indexes 
a[2:5]

array([2, 3, 4])

In [71]:
# For 2D Data slice items starting from index
a = np.array([[1,2,3],[3,4,5],[4,5,6]]) 
a[1:]  

array([[3, 4, 5],
       [4, 5, 6]])

In [72]:
#Slicing One Row
a[0]

array([1, 2, 3])

In [77]:
#Slicing One Column
a[...,1] 

array([2, 4, 5])

In [81]:
#Advance Indexing on 2D array
x = np.array([[1, 2], [3, 4]]) 
x 

array([[1, 2],
       [3, 4]])

In [86]:
x[0,1]

2

In [94]:
x = np.array([[1, 2,8], [3, 4,6],[5,9,7]]) 
x

array([[1, 2, 8],
       [3, 4, 6],
       [5, 9, 7]])

In [102]:
x[1:3,1:3] 

array([[4, 6],
       [9, 7]])

In [103]:
#Boolean Array Indexing
x[x > 5]

array([8, 6, 9, 7])

In [107]:
#DataSet
a = np.arange(0,60,5)
a = a.reshape(3,4)
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [117]:
#Iterating Over Array
for x in np.nditer(a):
   print(x)

0
5
10
15
20
25
30
35
40
45
50
55


In [118]:
a.T

array([[ 0, 20, 40],
       [ 5, 25, 45],
       [10, 30, 50],
       [15, 35, 55]])

In [116]:
#Iterating Over Array in Transpose matrix
b=a.T
c=b.copy(order = 'C')
for x in np.nditer(c):
   print(x)

0
20
40
5
25
45
10
30
50
15
35
55


# Array math
Basic mathematical functions operate elementwise on arrays, and are available both as operator overloads and as functions in the numpy module:

In [124]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [122]:
# Elementwise sum; both produce the array

print(x + y)

print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [123]:
# Elementwise difference; both produce the array
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [126]:
# Elementwise product; both produce the array
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [125]:
# Elementwise division; both produce the array
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [127]:
# Elementwise square root; produces the array
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [128]:
v = np.array([9,10])
w = np.array([11, 12])

# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

219
219


In [129]:
# Matrix / vector product; both produce the rank 1 array [29 67]
print(x.dot(v))
print(np.dot(x, v))

[29. 67.]
[29. 67.]


In [131]:
# Matrix / matrix product; both produce the rank 2 array
print(x.dot(y))
print(np.dot(x, y))

[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [133]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))  # Compute sum of all elements; prints "10"
print(np.sum(x, axis=0))  # Compute sum of each column; prints "[4 6]"
print(np.sum(x, axis=1))  # Compute sum of each row; prints "[3 7]"

10
[4 6]
[3 7]


In [134]:
x = np.array([[1,2], [3,4]])
print(x)    
print(x.T)  

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


In [135]:
# Note that taking the transpose of a rank 1 array does nothing:
v = np.array([1,2,3])
print(v)    
print(v.T)  

[1 2 3]
[1 2 3]


# Broadcasting

Broadcasting two arrays together follows these rules:

1. If the arrays do not have the same rank, prepend the shape of the lower rank array with 1s until both shapes have the same length.

2. The two arrays are said to be compatible in a dimension if they have the same size in the dimension, or if one of the arrays has size 1 in that dimension.

3. The arrays can be broadcast together if they are compatible in all dimensions.

4. After broadcasting, each array behaves as if it had shape equal to the elementwise maximum of shapes of the two input arrays.
5. In any dimension where one array had size 1 and the other array had size greater than 1, the first array behaves as if it were copied along that dimension

In [136]:

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)   # Create an empty matrix with the same shape as x

# Add the vector v to each row of the matrix x with an explicit loop
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [137]:
# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
vv = np.tile(v, (4, 1))   # Stack 4 copies of v on top of each other
print(vv)                 # Prints "[[1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]
                          #          [1 0 1]]"
y = x + vv  # Add x and vv elementwise
print(y)  # Prints "[[ 2  2  4
          #          [ 5  5  7]
          #          [ 8  8 10]
          #          [11 11 13]]"

[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]
[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [138]:
# Compute outer product of vectors
v = np.array([1,2,3])  # v has shape (3,)
w = np.array([4,5])    # w has shape (2,)
# To compute an outer product, we first reshape v to be a column
# vector of shape (3, 1); we can then broadcast it against w to yield
print(np.reshape(v, (3, 1)) * w)


[[ 4  5]
 [ 8 10]
 [12 15]]


In [139]:

# Add a vector to each row of a matrix
x = np.array([[1,2,3], [4,5,6]])
# x has shape (2, 3) and v has shape (3,) so they broadcast to (2, 3),
print(x + v)

[[2 4 6]
 [5 7 9]]


In [143]:

# Add a vector to each column of a matrix
# x has shape (2, 3) and w has shape (2,).
# If we transpose x then it has shape (3, 2) and can be broadcast
# against w to yield a result of shape (3, 2); transposing this result
# yields the final result of shape (2, 3) which is the matrix x with
# the vector w added to each column.
print((x.T + w).T)


[[ 5  6  7]
 [ 9 10 11]]


In [141]:
# Another solution is to reshape w to be a column vector of shape (2, 1);
# we can then broadcast it directly against x to produce the same
# output.
print(x + np.reshape(w, (2, 1)))


[[ 5  6  7]
 [ 9 10 11]]


In [142]:

# Multiply a matrix by a constant:
# x has shape (2, 3). Numpy treats scalars as arrays of shape ();
# these can be broadcast together to shape (2, 3)
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]]


# Changing Shape of Array

1	reshape --->Gives a new shape to an array without changing its data

2	flat --->A 1-D iterator over the array

3	flatten --->Returns a copy of the array collapsed into one dimension

4	ravel --->Returns a contiguous flattened array

In [146]:
#Reshape
x.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [154]:
#Flat
#This function returns a 1-D iterator over the array. It behaves similar to Python's built-in iterator.
x.flat[5]

6

In [156]:
#Flatten
#This function returns a copy of an array collapsed into one dimension
a.flatten()

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [158]:
a.flatten(order='F')

array([ 0, 20, 40,  5, 25, 45, 10, 30, 50, 15, 35, 55])

In [159]:
#ravel
#This function returns a flattened one-dimensional array. A copy is made only if needed. 
#The returned array will have the same type as that of the input array.
a.ravel()

array([ 0,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55])

In [252]:
a.ravel(order='F')

array([ 1, 20, 40,  5, 25, 45, 10, 30, 50, 15, 35, 55])

# Splitting Arrays

In [161]:
#Split
np.split(a,3)

[array([[ 0,  5, 10, 15]]),
 array([[20, 25, 30, 35]]),
 array([[40, 45, 50, 55]])]

In [167]:
#Horizontal Split
np.hsplit(a,1)

[array([[ 0,  5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55]])]

In [253]:
#Veritical Split
np.vsplit(a,1)

[array([[ 1,  5, 10, 15],
        [20, 25, 30, 35],
        [40, 45, 50, 55]])]

# Adding / Removing Elements in Array

In [172]:
#delete
np.delete(a,5)

array([ 0,  5, 10, 15, 20, 30, 35, 40, 45, 50, 55])

In [175]:
#insert
np.insert(a,5,25)

array([ 0,  5, 10, 15, 20, 25, 25, 30, 35, 40, 45, 50, 55])

In [251]:
#append
np.append(a,60)

array([ 1,  5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60])

# Arithmetic Operations

In [179]:
#Reciporcal
np.reciprocal(a)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in reciprocal
  
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in reciprocal
  


array([[-2147483648,           0,           0,           0],
       [          0,           0,           0,           0],
       [          0,           0,           0,           0]], dtype=int32)

In [181]:
#power
np.power(a,2)

array([[   0,   25,  100,  225],
       [ 400,  625,  900, 1225],
       [1600, 2025, 2500, 3025]], dtype=int32)

In [184]:
#mod
b = np.array([3])
np.mod(a,b) 

array([[0, 2, 1, 0],
       [2, 1, 0, 2],
       [1, 0, 2, 1]], dtype=int32)

In [188]:
#remainder
np.remainder(a,b) 

array([[0, 2, 1, 0],
       [2, 1, 0, 2],
       [1, 0, 2, 1]], dtype=int32)

In [189]:
a

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [196]:
#minimum row
np.amin(a,0)

array([ 0,  5, 10, 15])

In [197]:
#minimum column
np.amin(a,1)

array([ 0, 20, 40])

In [200]:
#maximum row
np.amax(a,0)

array([40, 45, 50, 55])

In [250]:
#maximum column
np.amax(a,0)

array([40, 45, 50, 55])

# Statistical Functions

In [205]:
#mean
np.mean(a)

27.5

In [206]:
#average
np.average(a)

27.5

In [207]:
#median
np.median(a)

27.5

In [208]:
#standard Deviation
np.std(a)

17.260262647673315

In [210]:
#variance
np.var(a)

297.9166666666667

In [217]:
#where condition
y=np.where(a> 20) 
y

(array([1, 1, 1, 2, 2, 2, 2], dtype=int64),
 array([1, 2, 3, 0, 1, 2, 3], dtype=int64))

In [249]:
#a[y]
a[np.where(a> 20) ]

array([25, 30, 35, 40, 45, 50, 55])

# Copies & Views

In [223]:
#View
b=a.view() 
b

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [227]:
b[0,0]=1
b

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [236]:
#In View Data replacement will happen
a

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [242]:
#In view Shape cant be changed
b.shape=4,3
b

array([[ 1,  5, 10],
       [15, 20, 25],
       [30, 35, 40],
       [45, 50, 55]])

In [243]:
a

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [231]:
#copy
c=a.copy()
c

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [233]:
c[0,0]=0
c

array([[ 0,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [235]:
a

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

In [247]:
#If we copied the data then shape and data replacement will not happen whatever happened its only for copied data.
c.shape=6,2
c

array([[ 0,  5],
       [10, 15],
       [20, 25],
       [30, 35],
       [40, 45],
       [50, 55]])

In [248]:
a

array([[ 1,  5, 10, 15],
       [20, 25, 30, 35],
       [40, 45, 50, 55]])

# Matrix Operations

In [255]:
#matlib.empty()
#The matlib.empty() function returns a new matrix without initializing the entries. 
np.empty((2,2))

array([[5., 6.],
       [7., 8.]])

In [257]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [261]:
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [280]:
#Random Variable
x=np.random.rand(9)
x

array([0.62518204, 0.06751484, 0.5683406 , 0.30299368, 0.8910095 ,
       0.76642452, 0.41567512, 0.40669446, 0.51028436])

In [281]:
#Random Variable
y=np.random.rand(9)
y

array([0.49108539, 0.25173308, 0.0459539 , 0.77020267, 0.26936908,
       0.37581809, 0.8914405 , 0.22515384, 0.97987231])

In [288]:
d = np.array([[1,2],[3,4]]) 
e = np.array([[11,12],[13,14]]) 

In [289]:
#Dot Product -- Matrix Multiplication
np.dot(d,e)

array([[37, 40],
       [85, 92]])

In [293]:
#Normal Multiplication 
#Note − 1*11 + 2*12 + 3*13 + 4*14 = 130
np.vdot(d,e)

130

In [297]:
#Matrix Multiplication
np.matmul(d,e)

array([[37, 40],
       [85, 92]])

In [299]:
D=np.array([[6,1,1], [4, -2, 5], [2,8,7]]) 

In [300]:
#Determinant
#6*(-2*7 - 5*8) - 1*(4*7 - 5*2) + 1*(4*8 - -2*2) = 360
np.linalg.det(D)

-306.0

# numpy.linalg.solve()
x + y + z = 6

2y + 5z = -4

2x + 5y - z = 27

A=[[1 1 1]
   [0 2 5]
   [2 5 -1]] 

X=[x y z]

B=[6
-4
27]

A*X=B

In [307]:
#Equation Solving
A=np.array([[1,1,1],[0,2,5],[2,5,-1]])
A

array([[ 1,  1,  1],
       [ 0,  2,  5],
       [ 2,  5, -1]])

In [311]:
B=np.array([[6],[-4],[27]])
B

array([[ 6],
       [-4],
       [27]])

In [313]:
#X Y Z
np.linalg.solve(A,B)

array([[ 5.],
       [ 3.],
       [-2.]])